### ISSUE TITLE
Group Selector Counters

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#45] opened 2016-05-20 17:54 UTC
Each tile in the Group Selector should display a counter with the number of unread/unanswered “leader” items in that group (we call this “priority zone content”). The backend provides activities in the sort order as described below. The Group Selector counters should always count the number of Priority Zone items. So, if there are 3 priority zone items in Save the Whales and 4 priority zone items in United States, then the All counter shows 7, the 3-person newsfeed icon shows 7, the US icon shows 4, and the Save the Whales icon shows 3.

This logic already existed in the app on the frontend, but I don't think the counters have been working correctly because of the newsfeed data not loading properly. I want to make sure that I gave all of this description so that you could better understand how its supposed to work.

(Backend sorting information below)
**Prioritized Zone, listed chronologically**
- All unread Petitions, unread Discussions, unanswered polls, unanswered fundraisers, unanswered events, unanswered boosted posts that are not expired
- Note: Counters/badges reflect the number of items that fall within this zone. Notification alerts are sent for everything in this zone.

**Non-Prioritized Zone, listed chronologically beginning _after _the oldest priority item**
- All Non-Boosted User Posts and Petitions that are not expired
- All previously-prioritized content that has been read (Petition/Discussion) or answered (Poll/Event/Fundraiser/Boosted Post) - the flag needs to be switched from true to false once the user has read the petition, read the discussion, answered the poll/fundraiser/event, or answered a boosted post. The mobile app will tell the server when a petition or discussion has been read. The server will automatically update the flag when a poll/fundraiser/event has been answered or a boosted post has been answered.
- Note: Non-boosted user posts are always treated chronologically with no special prioritization. Boosted user posts are prioritized like leader's posts.

**Expired Zone, listed chronologically beginning after the oldest non-expired, non-priority zone item.**
- All other activities that do not fit into the above two categories.

**Comment by petervojtek** [comment] 2016-07-12 07:24
duplicate of #130.

**Closed as completed by petervojtek** 2016-07-12 07:24 UTC
Labels: enhancement
