### ISSUE TITLE
Group Selector Filters

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#44] opened 2016-05-20 17:32 UTC
The Filters in the Group Selector do not work. They should filter the newsfeed to show content for that specific group. The “All” filter should show content from all of the user’s groups. The country group button should only show content from the user's country group. The save the whales group button should only show the Save the Whales group content, etc. 

The More button should display the current filter if not All, town, state, or country. To clarify, the group selector always has five buttons shown: All, Town, State, Country, More... When the user taps the "More" button, the addition tiles of other groups should appear. When a group tile is selected (e.g. "Save the Whales"), the More button is supposed to show that label while maintaining the "..." three-dots icon. It should use the acronym for the group if available.

**Comment by petervojtek** [comment] 2016-06-23 07:26
#71 is probably duplicate of this one.

**Comment by austinpapp** [comment] 2016-06-27 13:33
as stated above, this is being handled in #71

**Closed as completed by austinpapp** 2016-06-27 13:33 UTC
Labels: bug
