### ISSUE TITLE
Priority Zone Adjustment

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#210] opened 2016-09-08 14:59 UTC
I'm not sure if this is frontend or backend.

Unread Leader Petitions, Boosted User Petitions, and Leader News/Discussion items are each considered "non-priority zone" as soon as they're opened/viewed. They do not need to be signed to be considered "read/viewed"... I only tested this requirement with an unread leader petition (I did not test with boosted user petition or with unread leader-news/discussion item). 

Currently, the app is only moving the leader petition to non-priority zone once user signs petition. This is incorrect. App should move leader petition to non-priority zone as soon as the petition is opened and viewed (same with boosted user petition and with unread leader-news/discussion item.)

Note: For the issue described above, I am assuming that Peter10 is a leader in screenshot below. If Peter10 is not a leader, and he is a normal user, than why is his user petition appearing in priority zone? Unboosted user posts and unboosted user petitions do not appear in priority zone. They should appear in non-priority zone. (Per #212 and #167)

![screenshot_2016-09-08-08-27-16](https://cloud.githubusercontent.com/assets/7582457/18354276/f12dd1fe-75b2-11e6-98ee-904ea4b00f9f.png)

**Comment by jterps08** [comment] 2016-09-08 15:07
It is unclear whether or not this is a backend issue or a frontend issue. If backend logic is already correct, than it may be that the app is not signalling to the backend that something has been opened/viewed.

**Comment by petervojtek** [comment] 2016-09-08 16:37
@jterps08 , I will check this issue on frontend and assign to Igor with additional details if needed.

**Comment by petervojtek** [comment] 2016-09-09 06:34
@jterps08 , `Peter10 Peter10` is leader. I renaned him to `Peter10 is Leader` to prevent further confusion :)

Regarding the bug -- I fixed it (it was frontend issue). 
Currently it works as following:
1. there is activity item for POLL1 in priority zone -- usually it is one of the first items in the activity newsfeed. 
2. you enter the POLL1 detail and thus the item is no longer in priority zone.
3. you click Back and appear in the activity newsfeed again.
4. currently the activity item from POLL1 no longer holds the red dot, but it is still in the same place (order).
5. when you refresh the activity newsfeed (by pulling the newsfeed a bit) or new activity item arrives, the items will reorder and activity item for POLL1 will typically go out of sight in the activity newsfeed and you will have to scroll down to see it.

Please let me know if in step 4 you rather want the activity item for POLL1 immidiately take the new order (and effectively disappear from sight when there are more than few other priority items).

I find the existing behaviour better from UX point of view, because the item is not "immidiately lost of sight" when you return from it's detail, but the red dot disappears immidiately which gives the user feedback that the item is no longer "special".

**Comment by jterps08** [comment] 2016-09-09 12:27
I agree with this: "I find the existing behaviour better from UX point of view, because the item is not "immidiately lost of sight" when you return from it's detail, but the red dot disappears immidiately which gives the user feedback that the item is no longer "special"."

I just want to confirm the logic when you mention "POLL1"...
(Once answered, moves from priority zone to non-priority zone): Unanswered Polls, Unanswered Events, Unanswered Fundraisers/Crowdfunders, Unanswered Boosted Posts
(Once opened, moves from priority zone to non-priority zone): Unread/Unopened Petitions, Unread/Unopened News/Discussions, 
(If expired, moves to expired zone.) All content with expiration.

**Comment by petervojtek** [comment] 2016-09-09 14:38
> I just want to confirm the logic when you mention "POLL1"..

@jterps08 , I am getting confused :(

I am currently aware of there data types: Post, UserPetition, Poll:Petition, Poll:Event. 
Other data types have not been spotted in the mobile app so far :) and we should address them in some other issue first and only then solve their priority/not-priority zone.

Now, disregarding which of those four types an activity item is, it can arrive with attribute `zone` set to `prioritized`. If this happens, the mobile app will display red dot and move the item in front. 
There is no concept of "boosting" explicitly available in frontend and I would say if possible, let us try to avoid that term in this discussion as it only brings more congnitive load :)

Now I would like to ask for for each of those 4 data types (Post, UserPetition, Poll:Petition, Poll:Event):

When activity item of some particular type has `zone=prioritized`, what must happend to the item to became not-prioritized? Current implementation is probably wrong due to my misunderstanding and works as following:
- as soon as the item is read, it is out of priority zone.

**Comment by jterps08** [comment] 2016-09-09 15:13
@petervojtek This is a combination of issues, frontend and backend... I will try to explain as short as I can... A boosted Post or a boosted Petition should appear with zone set to 'prioritized' by backend. An unboosted user Post and an unboosted user Petition are not priority zone.... until they are boosted. (please confirm @igaponov).

These all start as priority zone: 
- new leader petition
- new leader event
- new leader fundraiser/crowdfunder (aka payment request)
- new leader poll
- new leader news (aka discussion)
- boosted user Petition
- boosted user Post

These start as non-priority zone:
- new user Post (not boosted)
- new user Petition (not boosted)

This is how Priority zone items become non-priority zone:
- If leader petition  is **read/opened** OR boosted user Petition is read/opened, it becomes non-priority zone. 
- If leader news/discussion is **read/opened**, it becomes non-priority zone.
- If boosted user Post is **answered**, it becomes non-priority zone.
- If leader event is **answered**, it becomes non-priority zone.
- If leader fundraiser is **answered**, it becomes non-priority zone.
- If leader poll is **answered**,, it becomes non-priority zone.

**Read/opened** = the user tapped on the item and viewed it from the Item Detail Screen OR they signed the petition (if its a petition). If leader petition, just viewing it will mark it read. If boosted user petition, just viewing it will mark it read. If either leader petition or boosted user petition, signing it can also mark it read (since user could sign from newsfeed or notification drawer without opening), but simply opening/viewing the petition will mark it as read, too... 
**Answered** = the user responded to the question. For a boosted post, that means submitting one of 3 answer choices: upvote, downvote, or ignore. For regular poll, that means submitting one of available multiple choice answers. For event, that means submitting one of available multiple choice answers. For fundraiser, that means submitting one of available multiple choice answers (fyi: all fundraisers include a $0 option), 

@igaponov - Can @petervojtek create all types of leader content with the Peter10 account using current API? Please confirm. Thanks. We need to create other types of content polls, petitions, discussions, fundraisers, and events for testing. I believe this is already complete, but need to confirm.

**Comment by igaponov** [comment] 2016-09-10 15:04
@jterps08 i'm working on boosted posts/petitions in https://github.com/PowerlineApp/powerline-mobile/issues/212 
Any user can create all types of leader content.

**Comment by jterps08** [comment] 2016-09-10 15:10
Thanks @igaponov ... Regarding: "Any user can create all types of leader content." I assume you mean if they have owner/manager rights, correct? Just want to make sure :-)

Peter - Igor gave the JTest1 account owner privileges for the Build Test Two group. JTest1 should be able to create leader content in Build Test Two (but not any other groups where he is not owner/manager).

**Comment by igaponov** [comment] 2016-09-10 15:15
@jterps08 yes, if they have privileges, they can create any type.

**Comment by petervojtek** [comment] 2016-09-11 07:37
thanks for additional explanation @jterps08 , now I understand what to do. 

In order to fix this for all leader content types, I will extend [the JS console helper](https://github.com/PowerlineApp/powerline-mobile/issues/221#issuecomment-246166632) to allow us to create all the the leader content types.

**Comment by petervojtek** [comment] 2016-09-12 06:56
@jterps08 , I tried to implement the [rules above](https://github.com/PowerlineApp/powerline-mobile/issues/210#issuecomment-245942901) but unfortunately I still find the too confusing. 

First, I have to avoid using the term `boosted` as the concept is not present in mobile app, in mobile app every activity item is either in priority zone, or not. 

Also I am confused by using two terms: `Read/opened`. Does `read` means something else than `opened`?  If they are the same, why you use two terms?

This is how I currently interpret the rules above, I am not sure if properly:
- Anything in priority zone that can be answered from activity newsfeed is marked as out-of-priority zone when answered
- Anything in priority zone is marked as out-of-priority zone when opened.

No more rules are needed, because item that can be anwered only from its detail must be first opened.

**Comment by jterps08** [comment] 2016-09-12 12:39
Peter - A few thoughts here:

"boosted" is a verb that I use to explain the process or action of when a push notification is sent to all group members for a user post or user petition. I would tell you what the exact flag/property on the post/petition is, but I can't read the **API DOC** ... I believe the property is "publish_status"=1 is boosted (according to this: https://github.com/PowerlineApp/powerline-server/wiki/Micropetition)

The two terms read/opened mean the same thing. To me there's no difference, but I didn't want to say "read" only because that could be misinterpreted. 

"Anything in priority zone that can be answered from activity newsfeed is marked as out-of-priority zone when answered" - Correct. _Answered_ from activity newsfeed OR item detail screen OR notification drawer callback. 
"Anything in priority zone is marked as out-of-priority zone when opened." - INCORRECT. _Opening_ a news/discussion item OR a leader-petition item OR a boosted user-petition item will mark it as out of priority zone. All other priority zone content must be _answered_.

"Answered" does not equal "Opened"

**Comment by petervojtek** [comment] 2016-09-12 14:13
@igaponov , UserPetition, Poll:Petition and Post have the ability to be answered/upvoted/downvoted from activity newsfeed without actually entering detail of the item.

The issue is, when such item has `zone` attrribute set to `prioritized` and user answers/votes the item from activity newsfeed, `zone` should be no longer `prioritized` (despite the user did not went into the item detail and thus backend have not received `is read` notification).

However currently backend still keeps the `zone` as `prioritized`.

Examples:

User Petition before sign:

```
{"zone":"prioritized","id":596,"title":"test UserPetition out of zone 1","description":"hi","description_html":"hi","sent_at":"2016-09-12T13:55:18.000Z","expire_at":null,"responses_count":0,"owner":{"id":64,"type":"user","official_title":"","first_name":"Peter1","last_name":"Peter1","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/576b9b633f3fa.jpeg"},"user":{"full_name":"Peter1 Peter1","id":64,"type":"user","official_title":"Peter1 Peter1","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/576b9b633f3fa.jpeg"},"entity":{"type":"user-petition","id":256,"group_id":1},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-09-12T13:55:18+0000","poll":null,"user_petition":{"is_subscribed":false},"post":null,"metadata":{"title":null,"description":null,"image":null,"url":null},"comments_count":1,"answers":[],"quorum":3}
```

User Petition after sign:

```
{"zone":"prioritized","id":596,"title":"test UserPetition out of zone 1","description":"hi","description_html":"hi","sent_at":"2016-09-12T13:55:18.000Z","expire_at":null,"responses_count":1,"owner":{"id":64,"type":"user","official_title":"","first_name":"Peter1","last_name":"Peter1","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/576b9b633f3fa.jpeg"},"user":{"full_name":"Peter1 Peter1","id":64,"type":"user","official_title":"Peter1 Peter1","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/576b9b633f3fa.jpeg"},"entity":{"type":"user-petition","id":256,"group_id":1},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-09-12T13:55:18+0000","poll":null,"user_petition":{"is_subscribed":false},"post":null,"metadata":{"title":null,"description":null,"image":null,"url":null},"comments_count":1,"answers":[{"option_id":1,"id":52,"created_at":"2016-09-12T13:56:11+0000"}],"quorum":3}
```

Poll:petition before sign:

```
{"zone":"prioritized","id":597,"title":"poll:petition 4","description":"bodytext","description_html":"bodytext","sent_at":"2016-09-12T13:58:47.000Z","expire_at":"2016-09-13T13:58:47.000Z","responses_count":0,"owner":{"id":285,"type":"group","group_type":3,"official_title":"San Diego","avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png"},"user":{"full_name":"Peter10 Is Leader","id":73,"type":"user","official_title":"Peter10 Is Leader","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"petition","id":227},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-09-12T13:58:47+0000","poll":{"is_subscribed":false,"answers_count":null},"user_petition":null,"post":null,"answers":[]}
```

Poll:petition after sign:

```
{"zone":"prioritized","id":597,"title":"poll:petition 4","description":"bodytext","description_html":"bodytext","sent_at":"2016-09-12T13:58:47.000Z","expire_at":"2016-09-13T13:58:47.000Z","responses_count":1,"owner":{"id":285,"type":"group","group_type":3,"official_title":"San Diego","avatar_file_path":"https://api-dev.powerli.ne/bundles/civixfront/img/default_group.png"},"user":{"full_name":"Peter10 Is Leader","id":73,"type":"user","official_title":"Peter10 Is Leader","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/577cb68e6f276.jpeg"},"entity":{"type":"petition","id":227},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-09-12T13:58:47+0000","poll":{"is_subscribed":false,"answers_count":1},"user_petition":null,"post":null,"answers":[{}],"answered":true,"answer":{"id":173,"option_id":361,"question":{"id":227}}}

```

Post before upvote:

```
{"zone":"prioritized","id":598,"title":"","description":"Post to test zone, test 2","description_html":"Post to test zone, test 2","sent_at":"2016-09-12T14:02:09.000Z","expire_at":"2016-09-13T14:02:09.000Z","responses_count":0,"owner":{"id":64,"type":"user","official_title":"","first_name":"Peter1","last_name":"Peter1","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/576b9b633f3fa.jpeg"},"user":{"full_name":"Peter1 Peter1","id":64,"type":"user","official_title":"Peter1 Peter1","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/576b9b633f3fa.jpeg"},"entity":{"type":"post","id":273,"group_id":1},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-09-12T14:02:09+0000","poll":null,"user_petition":null,"post":{"is_subscribed":false},"metadata":{"title":null,"description":null,"image":null,"url":null},"comments_count":0,"answers":[],"quorum":3}
```

Post after upvote:

```
{"zone":"prioritized","id":598,"title":"","description":"Post to test zone, test 2","description_html":"Post to test zone, test 2","sent_at":"2016-09-12T14:02:09.000Z","expire_at":"2016-09-13T14:02:09.000Z","responses_count":0,"owner":{"id":64,"type":"user","official_title":"","first_name":"Peter1","last_name":"Peter1","avatar_file_path":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/576b9b633f3fa.jpeg"},"user":{"full_name":"Peter1 Peter1","id":64,"type":"user","official_title":"Peter1 Peter1","avatar_file_name":"http://devpowerline.s3-website-eu-west-1.amazonaws.com/avatars/576b9b633f3fa.jpeg"},"entity":{"type":"post","id":273,"group_id":1},"picture":null,"read":false,"rate_up":null,"rate_down":null,"image_src":null,"updated_at":"2016-09-12T14:02:09+0000","poll":null,"user_petition":null,"post":{"is_subscribed":false},"metadata":{"title":null,"description":null,"image":null,"url":null},"comments_count":0,"answers":[{"id":113,"option":2,"created_at":"2016-09-12T14:05:25+0000"}],"quorum":3}
```

**Comment by igaponov** [comment] 2016-09-12 17:00
User Petition and Post are fixed (even old ones).
Poll:petition must be read to move to `non-prioritized`

**Comment by jterps08** [comment] 2016-09-12 17:18
Signing OR reading a **boosted user Petition** or **Poll:Petition** (leader petition) should result in move to non-priority zone.

**Comment by igaponov** [comment] 2016-09-12 17:27
@jterps08 I asked you in Slack, your answer:

```
jesse [10:55 PM]  
*Priority Zone*
all kinds of poll, except Petition and News - unanswered
leader petition  - unread (leader petitions never get boosted)
leader news - unread
user post - boosted and unvoted
user petition - (boosted and unread) OR (boosted and unsigned)
```

**Comment by jterps08** [comment] 2016-09-12 19:35
Leader petition is moved to non-priority zone after it is read **or signed.**

User Petition is in priority zone only if boosted. Moves to non-priority zone if it is read or signed. 

here's the point: If someone signs a petition from the newsfeed (which they can do without opening/viewing the petition), it should be moved to non-priority zone. The priority zone should only ever represent action items for the user to take.

**Comment by igaponov** [comment] 2016-09-13 03:17
Fixed

**Comment by petervojtek** [comment] 2016-09-13 07:22
ok, now it works as expected for poll:event, petition and userPetition.

for other content types we are blocked by #221

**Closed as completed by petervojtek** 2016-09-13 07:22 UTC
Labels: bug, P1 - High Priority
