### ISSUE TITLE
Friend Finder

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#11] opened 2016-02-17 02:44 UTC
We have added an endpoint that receives "hashed" e-mail addresses and phone numbers from the user and returns the same hashed e-mail addresses that are associated to an existing Powerline account. This is how we will be able to scan the user's contact address book and see 'who they already know' on Powerline already. The mobile app will scan the user's address book, send hashed e-mail address (or phone numbers) from user's address book to the Powerline server which will return the hashes of existing Powerline users so that the app can display a list of people that the user can request to follow... What does this mean exactly? Add a button to the Main Menu called "Find Friends". When tapped, this button will display the same screen as the Splash screen (Powerline logo) with a button that says "Search Address Book Now". When the Search Address Book Now button is pressed, the app will hash the e-mail addresses and phone numbers in the user's address book and send them to the Powerline server. Any returned hashes will be of registered Powerline users and those registered user's names should be displayed (with the same format/template as My Influences screen that lists group members along with a Follow button next to each person's name). Their avatar and name will link to that user's profile. The follow button will behave just like the follow button in the newsfeed. Igor can clarify the hash method - I believe it's SHA1. Igor has also built the endpoint.

**Comment by petervojtek** [comment] 2016-07-14 12:02
@igaponov , I would like to discuss on `GET /api/search/friends`:

The endpoint works properly, however I am not sure if GET is the best HTTP method for the use case.
The issue is that e.g. I have in a phone 1200+ email contacts. 
I am unable to send them in a single request due to:

```
response status: 200 OK

"<html>
↵<head><title>414 Request-URI Too Large</title></head>
↵<body bgcolor="white">
↵<center><h1>414 Request-URI Too Large</h1></center>
↵<hr><center>nginx/1.4.6 (Ubuntu)</center>
↵</body>
↵</html>
↵"
headers
```

I.e., all those 1200 emails are in request URI (as GET requests are not supposed to send any data in request body).

I can bypass the issue with the current endpoint by making serveral GET requests, each with e.g. 50 emails and then collect all the responses, but I am not sure if this is the best solution. 

 switching the endpoint from GET to POST will allow me tho send all the emails in one request body. On the other side, it makes perfect sense that the endpoint is GET, because it does not alters backend in any way. Maybe another option would be to alter nginx config to allow longer uris.

maybe you will suggest some better solution..

**Comment by jterps08** [comment] 2016-07-14 17:16
This is definitely low-priority, but I am open to any solutions you guys have. I think you understand the objective: we want to help people find their friends based on their address book so that we can help people follow each other, etc.

**Comment by petervojtek** [comment] 2016-07-16 13:54
after discussion with Austin: will make several GET requests so that no changes are required to be done to backend.

**Comment by petervojtek** [comment] 2016-07-19 08:32
@jterps08 , while waiting for other blocked bugs, I finished this feature.

The design is spartan, but it fully works:

<img width="440" alt="screen shot 2016-07-19 at 10 30 35" src="https://cloud.githubusercontent.com/assets/225506/16943415/f4b35518-4d9b-11e6-9fa9-eb61a82706b9.png">

I guess you imagined the design bit differently.. due to this reason I assign this issue to you, so that when you will be able to specify it more preciously, I can adjust it.

**Closed as completed by petervojtek** 2016-07-19 08:32 UTC
Labels: enhancement, low-priority

**Comment by jterps08** [comment] 2016-07-19 13:44
This is so cool - I wasn't expecting this! I'll keep the issue closed for now and we can come back to it later. Thanks, @petervojtek !
