### ISSUE TITLE
Newsfeed Red Dots for Priority Zone Items

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#47] opened 2016-05-20 18:34 UTC
The newsfeed used to display "red dots" next to items that were considered priority zone items. The counters represent the number of red dot items. For example, if the user has 7 priority zone items in the All feed, the All counter shows 7 and the first 7 items in the newsfeed each have red dots. The red dot disappears when the item is no longer in the priority zone. This functionality should still work, but it depends on newsfeed data to test.

**Comment by petervojtek** [comment] 2016-06-30 12:46
duplicate of #121.

**Closed as completed by petervojtek** 2016-06-30 12:46 UTC
Labels: bug

**Comment by jterps08** [comment] 2016-06-30 13:18
Anything that is considered Priority Zone (unread/unanswered as explained elsewhere) should have this little red dot in the UI. I will try to find screenshot showing it how it worked previously.

**Comment by petervojtek** [comment] 2016-06-30 14:32
not necessary, I found in in the html, it is a red dot below persons avatar/ng-letter.
