### ISSUE TITLE
Social Activity Feed Weird Behavior

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-mobile#298] opened 2016-09-23 14:40 UTC
I registered a new user Jon Stamos
Newsfeed is working correctly, showing all items from user's linked groups (town/state/country)
He has no followers and he is not following anyone. 
![screenshot_2016-09-23-10-35-23](https://cloud.githubusercontent.com/assets/7582457/18789652/b9dbd53e-8179-11e6-8980-f51d526a1b92.png)

Yet, Social Activity Feed is showing items from people he is not following.
![screenshot_2016-09-23-10-34-58](https://cloud.githubusercontent.com/assets/7582457/18789656/c2a86f38-8179-11e6-8e1a-c727ec65a39c.png)

**Comment by petervojtek** [comment] 2016-09-26 08:09
this is a backend issue.

**Comment by petervojtek** [comment] 2016-09-26 08:11
I also experience following behaviour -- as user Peter10 I can see my own activity in social feed of people I am following (i.e. I read the first entry like "I have commented on my own poll"):

<img width="843" alt="screen shot 2016-09-26 at 10 10 06" src="https://cloud.githubusercontent.com/assets/225506/18827142/903c049c-83d1-11e6-98d6-6e47b2a2263d.png">

**Comment by igaponov** [comment] 2016-09-28 13:54
@petervojtek I've added query parameter "following" for `GET /api/v2//user/social-activities`, use it for "Followings" tab.

**Comment by petervojtek** [comment] 2016-09-28 14:11
@igor, this is the case where it would be much better if i would be given the change to discuss the changes you are about to make to the API endpoint prior you actually implement them.

the problem is the way how you did it quite contradicts with the existing code in the mobile app code and would require some amount of time to adjust the mobile app code to it.

I am not sure why haven't you rather just fixed the `tab` attribute (values: `you/following`) which is already used and set for each activity provided via `GET /api/v2/user/social-activities` ? this way I would have to make no changes in the mobile app code because I already use that `tab` attribute.

**Comment by jterps08** [comment] 2016-09-28 14:20
Please connect via slack or Skype to determine best approach to address this issue. We want to avoid changes that have downstream impacts to mobile code whenever possible but not sure what's best solution in this case

**Comment by petervojtek** [comment] 2016-09-29 07:09
@jterps08 , this issue seems to became duplicate of https://github.com/PowerlineApp/powerline-mobile/issues/303#issuecomment-250387875

**Closed as completed by petervojtek** 2016-09-29 07:09 UTC
Labels: bug, P2 - Medium Priority
